In [2]:
%run dmp_discrete_output_omega.py -t ../Data/E_do/E_rang3.txt  -omg ../Data/Omega/omega_rang3.txt

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

In [30]:
import numpy as np
p=np.loadtxt('../Points/Points.txt')
p[:,0]

array([-514.15735 ,   28.830914,  281.32356 ])

In [33]:
%run dmp_discrete_ouput.py -points ../Points/Points.txt -omg ../Data/Omega/omega_rang3.txt -out ../Data/E_dmp/E_rang3_dmp.txt

In [10]:
path = np.loadtxt("E_rang3.txt").T

In [14]:
print(path)

[[-514.15735   -512.97194   -512.81387   -514.15735   -514.16494
  -514.16494   -514.33678   -514.18009   -512.65503   -510.00932
  -505.53733   -492.42699   -472.67486   -454.02386   -430.2753
  -404.95786   -382.91467   -361.24038   -344.16181   -328.16452
  -309.44107   -288.88786   -257.93033   -232.92938   -211.86181
  -193.73084   -169.29219   -145.10121   -117.67769    -90.406025
   -66.277781   -52.245624   -45.879994   -42.489755   -40.02961
   -37.958044   -38.193929   -39.36658    -39.488179   -39.488179
   -39.727388   -43.459418   -45.852056   -51.79938    -55.573842
   -60.658352   -66.722789   -71.23616    -69.834183   -59.260192
   -39.322071   -23.154572   -21.398552   -34.221172   -47.663131
   -56.563258   -66.629539   -68.170611   -66.629539   -57.602866
   -41.619014   -24.568569   -20.165457   -22.046179   -27.813076
   -35.404385   -45.192426   -60.285642   -65.585928   -65.585928 ]
 [  28.830914    25.762096    28.737244    28.830914    28.721956
    28.721956  

In [23]:
import numpy as np
p=np.loadtxt('../IK/QD.txt')
p.shape

(24200, 3)

In [26]:
24200/121

200.0

In [27]:
e=p.reshape(121,200,3)
e[1]

array([[-334.54270009,  301.36897048,  488.36146001],
       [-334.44501194,  300.13413534,  489.24368805],
       [-334.3281879 ,  299.08076347,  490.00148155],
       [-334.1786022 ,  298.16204433,  490.66543144],
       [-333.98267224,  297.33037932,  491.26676364],
       [-333.72898834,  296.54376112,  491.83309484],
       [-333.41570894,  295.77814316,  492.38066979],
       [-333.05542864,  295.03553889,  492.9092806 ],
       [-332.66881195,  294.33309524,  493.40913822],
       [-332.27764274,  293.69118723,  493.86835823],
       [-331.90364768,  293.13130843,  494.27429204],
       [-331.56845856,  292.67588434,  494.61364135],
       [-331.29254217,  292.34483135,  494.87388231],
       [-331.09203976,  292.14561841,  495.0473335 ],
       [-330.97730385,  292.06862039,  495.13306738],
       [-330.95573558,  292.09586554,  495.13336587],
       [-331.03437376,  292.20901717,  495.0504864 ],
       [-331.22029109,  292.39053711,  494.886203  ],
       [-331.52043497,  292.

In [8]:
p[1]

array([-334.44501194,  300.07105066,  489.24368805, -334.44501194,
        300.13413534,  489.24368805, -334.44501194,  300.19722003,
        489.24368805, -334.44501194,  300.26030471,  489.24368805,
       -334.44501194,  300.3233894 ,  489.24368805, -334.44501194,
        300.38647408,  489.24368805, -334.44501194,  300.44955877,
        489.24368805, -334.44501194,  300.51264346,  489.24368805,
       -334.44501194,  300.57572814,  489.24368805, -334.44501194,
        300.63881283,  489.24368805, -334.44501194,  300.70189751,
        489.24368805, -334.43577302,  300.07105066,  489.24368805,
       -334.43577302,  300.13413534,  489.24368805, -334.43577302,
        300.19722003,  489.24368805, -334.43577302,  300.26030471,
        489.24368805, -334.43577302,  300.3233894 ,  489.24368805,
       -334.43577302,  300.38647408,  489.24368805, -334.43577302,
        300.44955877,  489.24368805, -334.43577302,  300.51264346,
        489.24368805, -334.43577302,  300.57572814,  489.24368